runtime: python27
api_version: 1
threadsafe: true

env_variables:
        GCLOUD_PROJECT: 's3609565-cc-a2'

libraries:
- name: ssl
  version: latest

# [START handlers]
handlers:
- url: /bootstrap
  static_dir: bootstrap
- url: /static
  static_dir: static
- url: /upload
  script: main.app
- url: /user
  script: main.app
- url: /
  static_files: static/view.html
  upload: static/view.html

# [END handlers]
